### ISSUE TITLE
AttributeError: 'AnnasArchiveStore' object has no attribute 'working_mirror'

### ISSUE THREAD

**Issue by yiranzhimo** [ScottBot10/calibre_annas_archive#2]
Calibre version: 7.4

After installing this plugin, I tried to open the store as shown in the screenshot. 

<img width="1375" alt="截屏2024-01-24 21 11 28" src="https://github.com/ScottBot10/calibre_annas_archive/assets/40296363/b41abb28-b4e6-4f8c-9eae-8bfc7039bd4a">

There was an error:

> calibre, version 7.4.0
> 错误： 未处理的异常: <b>AttributeError</b>:'AnnasArchiveStore' object has no attribute 'working_mirror'
> Traceback (most recent call last):
>   File "calibre/gui2/actions/store.py", line 127, in open_store
>   File "calibre_plugins.store_annas_archive.annas_archive", line 92, in open
>     url = self.working_mirror
>           ^^^^^^^^^^^^^^^^^^^
> AttributeError: 'AnnasArchiveStore' object has no attribute 'working_mirror'

**Comment by adrianmihalko** [comment]
Same problem.

**Comment by ScottBot10** [comment]
Fixed in https://github.com/ScottBot10/calibre_annas_archive/commit/dde0dc4ac929a30a539140958945da50e2e42bb6. Use the newest release to get the update.
