### ISSUE TITLE
Downloads that pull from libgen are met with 404 error

### ISSUE THREAD

**Issue by brennanmuir** [ScottBot10/calibre_annas_archive#3]
Search for a book, begins to download using libgen link, download fails with 404 error. When I use the libgen link provided in the error, I reach a forbidden page.
```
calibre, version 7.5.1 (linux, embedded-python: True)
Failed to download e-book: Failed: Downloading Harry Potter and the Sorcerer's Stone.libgen.li.epub

Starting job: Downloading Harry Potter and the Sorcerer's Stone.libgen.li.epub 
Job: "Downloading Harry Potter and the Sorcerer's Stone.libgen.li.epub" failed with error: 
Traceback (most recent call last):
  File "calibre/gui2/threaded_jobs.py", line 82, in start_work
  File "calibre/gui2/ebook_download.py", line 84, in __call__
  File "calibre/gui2/ebook_download.py", line 100, in _download
  File "calibre/gui2/ebook_download.py", line 67, in download_file
  File "mechanize/_mechanize.py", line 257, in open
  File "mechanize/_mechanize.py", line 313, in _mech_open
mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper: HTTP Error 404: Not Found
 
Called with args: (<calibre.gui2.ui.Main object at 0x15096a951cf0>, None, 'http://libgen.li/https://cdn2.booksdl.org\\get.php?md5=f3c217db4187442b3751070ef7d90e4a&key=8B0ATCEIGBQ9KOHI', "Harry Potter and the Sorcerer's Stone.libgen.li.epub", '', True, [], <bound method StorePlugin.create_browser of <calibre_plugins.store_annas_archive.annas_archive.AnnasArchiveStore object at 0x1509358d4710>>) {'notifications': <queue.Queue object at 0x15090fb7c1d0>, 'abort': <threading.Event at 0x15090f93d110: unset>, 'log': <calibre.utils.logging.GUILog object at 0x15090fb7e450>} 
```

**Comment by Princeofthebow** [comment]
I am met with a very similar error, using Calibre 5.12. on Debian:

`calibre, version 5.12.0 (linux, embedded-python: False)
Failed to download e-book: Failed: Downloading Occhio di capra.libgen.li.epub

Starting job: Downloading Occhio di capra.libgen.li.epub 
Job: "Downloading Occhio di capra.libgen.li.epub" failed with error: 
Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/gui2/threaded_jobs.py", line 83, in start_work
    self.result = self.func(*self.args, **self.kwargs)
  File "/usr/lib/calibre/calibre/gui2/ebook_download.py", line 85, in __call__
    dfilename = self._download(cookie_file, url, filename, save_loc, add_to_lib, create_browser)
  File "/usr/lib/calibre/calibre/gui2/ebook_download.py", line 101, in _download
    return download_file(url, cookie_file, filename, create_browser=create_browser)
  File "/usr/lib/calibre/calibre/gui2/ebook_download.py", line 68, in download_file
    with closing(br.open(url)) as r:
  File "/usr/lib/python3/dist-packages/mechanize/_mechanize.py", line 257, in open
    return self._mech_open(url_or_request, data, timeout=timeout)
  File "/usr/lib/python3/dist-packages/mechanize/_mechanize.py", line 313, in _mech_open
    raise response
mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper: HTTP Error 404: Not Found
 
Called with args: (<calibre.gui2.ui.Main object at 0x7fb57d667940>, None, 'http://libgen.li/https://cdn3.booksdl.org\\get.php?md5=debe0e2eca96cdcf035543bd01365fdb&key=RGAYXREFJOOE98QM', 'Occhio di capra.libgen.li.epub', '', True, [], <bound method StorePlugin.create_browser of <calibre_plugins.store_annas_archive.annas_archive.AnnasArchiveStore object at 0x7fb563b06640>>) {'notifications': <queue.Queue object at 0x7fb5491ae3a0>, 'abort': <threading.Event object at 0x7fb5491ae9a0>, 'log': <calibre.utils.logging.GUILog object at 0x7fb5491ae2b0>} 
`

**Comment by Princeofthebow** [comment]
I think the issues is around here https://github.com/ScottBot10/calibre_annas_archive/blob/eac3aff2debcb991c66d0e81d0cdf19dd66d8d33/annas_archive.py#L157

if I am reading your code correctly, @ScottBot10 the way tou handle the link prefix is the issue.

@brennanmuir I have no direct experience with plugin development but if all is lost I can try to sort this out. Do you have experience?

**Comment by ScottBot10** [comment]
Fixed in https://github.com/ScottBot10/calibre_annas_archive/commit/dde0dc4ac929a30a539140958945da50e2e42bb6. Use the newest release to get the update.
