### ISSUE TITLE
Couldn't find any books matching your query

### ISSUE THREAD

**Issue by mtfreitasf** [ScottBot10/calibre_annas_archive#5]
ScottBot10, hi,

I have just installed your plugin in calibre, following the instructions. I checked the configuration and the mirror is correctly set. But when I try to search anything in the Get Books window, I keep getting the message above. When I try other stores such as Amazon, I can find the books. Is your plugin still working with version 7.19 of Calibre? Do I need to configure anything else? Thank you and best regards, Marcos

**Comment by Nittola** [comment]
> ScottBot10, hi,
> 
> I have just installed your plugin in calibre, following the instructions. I checked the configuration and the mirror is correctly set. But when I try to search anything in the Get Books window, I keep getting the message above. When I try other stores such as Amazon, I can find the books. Is your plugin still working with version 7.19 of Calibre? Do I need to configure anything else? Thank you and best regards, Marcos

Same issue. I have the flatpak version of Calibre. After installing the plugin and go to "Get Book" section, I selected Anna's Archive from the Shops List and searched for a book, but I got "Couldn't find any books matching your query". Tried to configure the plugin by selecting language, books, access, font but nothing. I even added in the mirrors the version of the website for my language.

Running Pop!_OS, Calibre 7.20 (flatpak from Pop!_Shop) and 0.2.3 plugin
![Schermata del 2024-10-23 11-01-26](https://github.com/user-attachments/assets/186c1ddb-8999-41be-9559-a2edfcfebe17)

**Comment by CanuckChris** [comment]
Same problem here, nothing can be found regardless of the search string.

**Comment by ScottBot10** [comment]
Fixed in https://github.com/ScottBot10/calibre_annas_archive/commit/dde0dc4ac929a30a539140958945da50e2e42bb6. Use the newest release to get the update.

**Comment by mtfreitasf** [comment]
I don't know if I can comment on closed issues but thank you, it is working now.

**Comment by Jlmbles** [comment]
Seems like this issue has came back for me on the latest 0.2.4.

**Comment by mtfreitasf** [comment]
I just tested on calibre 7.24 and 0.2.4. It is working. I searched for a book and a list shows in the dialog. I ask to open it in the external browser and it goes to the download page.

**Comment by Jlmbles** [comment]
> I just tested on calibre 7.24 and 0.2.4. It is working. I searched for a book and a list shows in the dialog. I ask to open it in the external browser and it goes to the download page.

Thanks for testing. I've just figured out my ISP is blocking access to Anna's Archive for some reason! It's working for me now while using a VPN at least.

**Comment by c00l4p3** [comment]
I have this problem, even using a VPN
